Default: &defaults
  database: class-load.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: class-load_test.sqlite3
  <<: *defaults

Staging:
  database: class-load_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: class-load_production.sqlite3
  poolsize: 100
  <<: *defaults
